AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: DynamoUsers


Parameters:
  DatabaseTableName:
    Type: String
    Default: users

Resources:
  UsersGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Tracing: Active
      CodeUri: src/
      Handler: index.lambdaHandler
      Runtime: nodejs14.x
      Timeout: 30
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DatabaseTableName
  UsersPublicTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DatabaseTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "name"
          AttributeType: "S"
        - AttributeName: "age"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "name"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: sortbyAge
          KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: age
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
